// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Actor struct {
	ID        string `json:"id"`
	Code      string `json:"Code"`
	Head      string `json:"Head"`
	Nonce     string `json:"Nonce"`
	Balance   string `json:"Balance"`
	StateRoot string `json:"StateRoot"`
	Height    string `json:"Height"`
}

type Address struct {
	ID    string `json:"id"`
	Str   string `json:"str"`
	Actor *Actor `json:"actor"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type QueryMessage struct {
	Messages []*Message `json:"messages"`
}

type QueryUser struct {
	Users []*User `json:"users"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FilUnit string

const (
	FilUnitFil      FilUnit = "Fil"
	FilUnitAttoFil  FilUnit = "AttoFil"
	FilUnitFemtoFil FilUnit = "FemtoFil"
	FilUnitPicoFil  FilUnit = "PicoFil"
	FilUnitNanoFil  FilUnit = "NanoFil"
)

var AllFilUnit = []FilUnit{
	FilUnitFil,
	FilUnitAttoFil,
	FilUnitFemtoFil,
	FilUnitPicoFil,
	FilUnitNanoFil,
}

func (e FilUnit) IsValid() bool {
	switch e {
	case FilUnitFil, FilUnitAttoFil, FilUnitFemtoFil, FilUnitPicoFil, FilUnitNanoFil:
		return true
	}
	return false
}

func (e FilUnit) String() string {
	return string(e)
}

func (e *FilUnit) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilUnit", str)
	}
	return nil
}

func (e FilUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
